import { expect, type Locator, type Page } from '@playwright/test';

/**
 * Page Object for the “生成测试用例” page.
 *
 * The object intentionally uses accessible names and stable placeholders
 * instead of CSS classes generated by the UI framework.
 */
export class GenerateTestCasesPage {
  readonly page: Page;

  readonly modelButton: Locator;
  readonly prdFileInput: Locator;
  readonly prdUploadZone: Locator;
  readonly documentTextArea: Locator;
  readonly pageSourceNameInput: Locator;
  readonly pageSourceTextArea: Locator;
  readonly pageSourceFileInput: Locator;
  readonly customFieldInput: Locator;
  readonly generateButton: Locator;
  readonly generateScriptButton: Locator;

  constructor(page: Page) {
    this.page = page;

    this.modelButton = page.getByRole('button', { name: /选择模型/ });
    this.prdFileInput = page.locator('input[type="file"][accept*=".md"]').first();
    this.prdUploadZone = page.getByRole('button').filter({
      hasText: '点击选择或拖拽文件到此处',
    });
    this.documentTextArea = page.getByRole('textbox', {
      name: '测试用例文档输入框',
    });
    this.pageSourceNameInput = page.getByRole('textbox', {
      name: '第 1 个源码所属页面标识',
    });
    this.pageSourceTextArea = page.getByRole('textbox', {
      name: '页面A的HTML源码',
    });
    this.pageSourceFileInput = page.locator('input[type="file"]').nth(1);
    this.customFieldInput = page.getByPlaceholder('例如：所属迭代、关联需求单号');
    this.generateButton = page.getByRole('button', { name: '开始生成', exact: true });
    this.generateScriptButton = page.getByRole('button', {
      name: '生成自动化测试脚本',
    });
  }

  async goto(): Promise<void> {
    await this.page.goto('https://prd-to-testcase.yangf999212.workers.dev');
  }

  async expectLoaded(): Promise<void> {
    await expect(
      this.page.getByRole('heading', { name: '生成测试用例' }),
    ).toBeVisible();
    await expect(this.page.getByText('上传 PRD 文档', { exact: true })).toBeVisible();
  }

  async openModelSelector(): Promise<void> {
    await this.modelButton.click();
  }

  async selectModel(modelName: string): Promise<void> {
    await this.openModelSelector();
    await this.page.getByRole('option', { name: modelName }).click();
  }

  async uploadPrd(filePath: string): Promise<void> {
    const fileChooserPromise = this.page.waitForEvent('filechooser');
    await this.prdUploadZone.click();
    const fileChooser = await fileChooserPromise;
    await fileChooser.setFiles(filePath);
    await expect(this.generateButton).toBeVisible({
      timeout: 30_000,
    });
    await expect(this.generateButton).toBeEnabled();
  }

  async enterDocument(text: string): Promise<void> {
    await this.documentTextArea.fill(text, { force: true });
  }

  async addPageSource(pageName: string, html: string): Promise<void> {
    await this.pageSourceNameInput.fill(pageName);
    await this.pageSourceTextArea.fill(html);
  }

  async uploadPageSource(filePath: string): Promise<void> {
    await this.pageSourceFileInput.setInputFiles(filePath);
  }

  async addCustomField(fieldName: string): Promise<void> {
    await this.customFieldInput.fill(fieldName);
    await this.page.getByRole('button', { name: '添加' }).click();
  }

  async setVisibleFields(fields: string[]): Promise<void> {
    for (const field of fields) {
      await this.page.getByRole('button', { name: field, exact: true }).click();
    }
  }

  async generate(): Promise<void> {
    await this.generateButton.scrollIntoViewIfNeeded();
    await this.generateButton.click();
  }

  async expectGeneratedCases(): Promise<void> {
    await expect(this.page.getByText(/生成完成：\d+ 条用例/)).toBeVisible({
      timeout: 120_000,
    });
    await expect(this.page.getByRole('tab', { name: /测试用例（\d+）/ })).toBeVisible();
  }

  async generateAutomationScript(): Promise<void> {
    await this.generateScriptButton.click();
  }

  async expectUploadPrompt(): Promise<void> {
    await expect(this.page.getByRole('button', { name: '请先上传文档' })).toBeVisible();
  }
}
